services:
  postgres:
    image: postgres:16
    container_name: wishlist-postgres
    environment:
      POSTGRES_DB: wishlist_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: carvajal-wishlist-backend:latest
    container_name: wishlist-backend
    depends_on:
      - postgres
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/wishlist_db
      DB_USERNAME: postgres
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8081:8080"

volumes:
  postgres_data: